### PR TITLE
fix(vue-tsc): support volar v1.0.14

### LINKED ISSUE #193: vue-tsc v1.0.14 throws with ``
### Describe the bug

Volar v1.0.14 has just been released and there are some changes,
in particular https://github.com/johnsoncodehk/volar/commit/e5f7b230717a06988cff71df1ae4ffaaa24da166#diff-5270d6425aa3f2991337ef48a11f7e996d30adf2618e5c2428077ff2c8a8f149
that renames `proxy.ts` to `index.ts`.

Using vite-plugin-checker with vue-tsc v1.0.14 throws:

```
Error: Cannot find module 'vue-tsc/out/proxy'
Require stack:
- /home/circleci/redacted/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/prepareVueTsc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at Object.<anonymous> (/home/circleci/redacted/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/prepareVueTsc.js:39:28)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/circleci/redacted/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/main.js:42:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/circleci/redacted/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/prepareVueTsc.js'
  ]
}
```

### Reproduction

```
npm create vue vue-tsc-v1.0.14 -- --typescript
cd vue-tsc-v1.0.14
npm i
npm i --save-dev --save-exact vite-plugin-checker
```

Enables vite-plugin checker for vue-tsc:
```ts
import checker from 'vite-plugin-checker'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), checker({
    vueTsc: true
  })],
```

then start:
```
npm run dev
```

Throws:
```
> vue-tsc-v1.0.14@0.0.0 dev
> vite

error when starting dev server:
Error: Cannot find module 'vue-tsc/out/proxy'
Require stack:
- /Users/cedric/Code/temp/vue-tsc-v1.0.14/node_modules/vite-plugin-checker/dist/cjs/checkers/vueTsc/prepareVueTsc.js
```

### Expected behavior

Should start without error

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.86 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.volta/tools/image/node/16.17.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.19.3 - ~/.volta/tools/image/npm/8.19.3/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    vite-plugin-checker: 0.5.2 => 0.5.2
```

### Additional context

This only breaks with vue-tsc v1.0.14, reverting to v1.0.13 works

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by cexbrayat**
Fixes #193

volar v1.0.14 renamed the `proxy.ts` file in `index.ts` and changed `createProgramProxy` into `createProgram`.

### CODE REVIEW

**Comment by emosheeep** [comment]
Same problems here.

**Comment by johnsoncodehk** [comment]
I will shim vue-tsc/out/proxy.js for v1.0.x, and planed to remove the shim in v1.1 and later.

File: packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ const _require = createRequire(import.meta.url)
 const _filename = fileURLToPath(import.meta.url)
 const _dirname = dirname(_filename)
 
-const proxyPath = _require.resolve('vue-tsc/out/proxy')
+const proxyPath = _require.resolve('vue-tsc/out/index')
```
Comment (fi3ework) [inline packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts:11]: I think we should still be compatible with `vue-tsc/out/proxy` for a few days until we remove it in a breaking version in the future. So detecting these two files and deciding which to patch will be great at this time.

Comment (cexbrayat) [reply packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts:11]: @johnsoncodehk shimed it in v10.16 See https://github.com/johnsoncodehk/volar/commit/5d7581e396e7811ab51fad9494e25c56771e5a98
Do you still think it's worth handling both?

Comment (fi3ework) [reply packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts:11]: Yes, some users might still install the latest vite-plugin-checker and old version of vue-tsc in the future. Since we can be compatible with both at a very low cost, we can support the old version for longer bug fixes and new features and drop it in the future breaking change version.

Comment (cexbrayat) [reply packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts]: @fi3ework 👍 done! It now tries to read /out/index, then falls back to /out/proxy if not found
I tested locally with vue-tsc v1.0.13 (/out/proxy), v1.0.14 (/out/index) and v1.0.16 (/out/proxy shimed)

File: packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts [hunk 2]
```diff
@@ -34,7 +41,7 @@ const textToReplace: { target: string; replacement: string }[] = [
     target: `function createProgram(rootNamesOrOptions, _options, _host, _oldProgram, _configFileParsingDiagnostics) {`,
     replacement: `function createProgram(rootNamesOrOptions, _options, _host, _oldProgram, _configFileParsingDiagnostics) { return require(${JSON.stringify(
       proxyPath
-    )}).createProgramProxy(...arguments);`,
+    )}).createProgram(...arguments);`,
```
Comment (fi3ework) [inline packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts:44]: should be be `createProgramProxy` when patching `vue-tsc/out/proxy` as before and `createProgram` for `vue-tsc/out/index`.

Comment (cexbrayat) [reply packages/vite-plugin-checker/src/checkers/vueTsc/prepareVueTsc.ts]: Of course, thanks 👍

**Review by fi3ework — APPROVED** [review]

**Comment by fi3ework** [comment]
Thanks!

**Comment by theoephraim** [comment]
@fi3ework - I'm seeing this issue again on latest versions of things... maybe @johnsoncodehk deleting the extra proxy file changed something?

**Comment by fi3ework** [comment]
Tracks in https://github.com/fi3ework/vite-plugin-checker/issues/193.
